services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tel_bot
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: bot_redis
    ports:
      - "6379:6379"