"""add phone_number and email

Revision ID: 1ab10f8fea72
Revises: a04809a7e40b
Create Date: 2025-01-09 18:09:53.557815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab10f8fea72'
down_revision: Union[str, None] = 'a04809a7e40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phoneNumber', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
